-- AlterTable
ALTER TABLE "products" 
ADD COLUMN IF NOT EXISTS "micron_rating" TEXT,
ADD COLUMN IF NOT EXISTS "flow_rate" TEXT,
ADD COLUMN IF NOT EXISTS "max_pressure" TEXT,
ADD COLUMN IF NOT EXISTS "temperature_range" TEXT,
ADD COLUMN IF NOT EXISTS "efficiency" TEXT,
ADD COLUMN IF NOT EXISTS "attributes" JSONB,
ADD COLUMN IF NOT EXISTS "outer_diameter" TEXT,
ADD COLUMN IF NOT EXISTS "inner_diameter" TEXT,
ADD COLUMN IF NOT EXISTS "length" TEXT,
ADD COLUMN IF NOT EXISTS "weight" TEXT,
ADD COLUMN IF NOT EXISTS "thread_size" TEXT,
ADD COLUMN IF NOT EXISTS "gasket_od" TEXT,
ADD COLUMN IF NOT EXISTS "gasket_id" TEXT;
